---
- name: Prepare
  hosts: docker
  gather_facts: false
  become: true
  tasks:
  - name: Install_python_for_ansible
    ansible.builtin.raw: test -e /usr/bin/python || apt -y update && apt install -y python3
    changed_when: false

- name: Install docker
  gather_facts: true
  hosts: docker
  remote_user: pi
  become: true
  roles:
    - docker

# ansible all -m ping --ask-vault-pass
# ansible-galaxy install -f -r docker_requierements.yml
# ansible-playbook docker.yml --ask-vault-pass
