---
- name: Prepare
  hosts: docker
  gather_facts: false
  become: true
  tasks:
  - name: Install_python_for_ansible
    ansible.builtin.raw: test -e /usr/bin/python || apt -y update && apt install -y python3
    changed_when: false

- name: Install_k8s
  hosts: k8s_workers, k8s_masters
  gather_facts: true
  roles:
    - role: install_k8s

- name: Setup_master
  hosts: k8s_masters
  roles:
    - role: configure_master

- name: Join_workers
  hosts: k8s_workers
  roles:
    - role: join_workers

# ansible all -m ping
# ansible-galaxy install -f -r k8s_requierements.yml
# ansible-playbook docker.yml --ask-vault-pass
