- hosts: masters
  become: yes
  
  tasks:
    - name: Pull the images that kubeadm requires.
      become: yes
      become_user: {{ ansible_user }}
      shell: kubeadm config images pull --cri-socket /run/containerd/containerd.sock

    - name: Initialize the cluster
      become: yes
      become_user: {{ ansible_user }}
      shell: |
        kubeadm init
        --pod-network-cidr={{ cidr }} \
        --cri-socket /run/containerd/containerd.sock \
        --upload-certs \
        --control-plane-endpoint=k8smaster.example.net \
        --skip-phases=addon/kube-proxy
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become: yes
      become_user: {{ ansible_user }}
      become_method: sudo
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: {{ ansible_user }}
        group: {{ ansible_user }}
        mode: 0755

    - name: Copies admin.conf to user's kube config
      become: yes
      become_user: root
      become_method: sudo
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: {{ ansible_user }}
        group: {{ ansible_user }}
        mode: '0644'

    - name: Remove the cache directory.
      become_user: {{ ansible_user }}
      become_method: sudo
      become: yes
      file: 
        path: /home/{{ ansible_user }}/.kube/cache
        state: absent

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: {{ ansible_user }}
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Print debug 
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

    - name: Configure kubectl command auto-completion.
      lineinfile:
        dest: /home/{{ ansible_user }}/.bashrc
        line: 'source <(kubectl completion bash)'
        insertafter: EOF