---
# vars file for deploy
pre_packages:
  - ca-certificates
  - curl
  - lsb-release

config_cri:
  - net.bridge.bridge-nf-call-iptables
  - net.ipv4.ip_forward
  - net.bridge.bridge-nf-call-ip6tables

pre_packages_docker:
  - curl
  - wget
  - apt-transport-https

packages_docker:
  - kubelet
  - kubeadm
  - kubectl
