---
- name: Restart and enable containerd
  ansible.builtin.systemd:
    daemon_reload: true
    restarted: true
    enabled: true
    name: containerd

- name: Restart systemd
  ansible.builtin.systemd:
    state: restarted
    become: true
