---
- name: Apply sysctl params systemctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Restart and enable containerd
  ansible.builtin.systemd:
    daemon_reload: true
    restarted: true
    enabled: true
    name: containerd

- name: Hold kubelet, kubeadm, kubectl
  ansible.builtin.dpkg_selections:
    selection: hold
    name:
      - kubelet
      - kubeadm
      - kubectl

- name: Enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
