---
- name: Restart systemd
  ansible.builtin.systemd:
    restarted: true
    become: true

- name: Restart and enable containerd
  ansible.builtin.systemd:
    daemon_reload: true
    restarted: true
    enabled: true
    name: containerd

- name: Hold kubelet, kubeadm, kubectl
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
