- name: Pull the images that kubeadm requires
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: /
    kubeadm config images pull --cri-socket /run/containerd/containerd.sock
  changed_when: false

- name: Initialize the cluster
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    kubeadm init
    --pod-network-cidr={{ cidr }} \
    --cri-socket /run/containerd/containerd.sock \
    --upload-certs \
    --control-plane-endpoint=k8smaster.example.net \
    --skip-phases=addon/kube-proxy
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Create .kube directory
  become: true
  become_user: "{{ ansible_user }}"
  become_method: sudo
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copies admin.conf to user's kube config
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Remove the cache directory
  become_user: "{{ ansible_user }}"
  become_method: sudo
  become: true
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube/cache
    state: absent

- name: Get the token for joining the worker nodes
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubernetes_join_command
  changed_when: false

- name: Print debug
  ansible.builtin.debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  become: true
  ansible.builtin.copy:
    local_action: copy
    content: "{{ kubernetes_join_command.stdout_lines[0] }}"
    dest: "/tmp/kubernetes_join_command"
    mode: 0777

- name: Configure kubectl command auto-completion.
  ansible.builtin.lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    line: "source <(kubectl completion bash)"
    insertafter: EOF
