---
- name: Install docker
  hosts: all
  become: true
  remote_user: pi
  become_method: sudo
  become_user: root
  gather_facts: true
  roles:
    - { role: docker, when: ansible_system == 'Linux' }
