---
- name: Install docker.
  hosts: all
  remote_user: pi
  become: true
  tasks:
  - name: Update and upgrade apt packages.
    ansible.builtin.apt:
      upgrade: true
      update_cache: true
      cache_valid_time: 86400 # One day

  - name: Install dependencies.
    ansible.builtin.apt:
      update_cache: true
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present

  - name: Add signing key.
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      state: present

  - name: Add repository into sources list.
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ ansible_architecture }}] \
      https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: Install dependencies.
    ansible.builtin.apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: present
      update_cache: true

  - name: Add adminstrator to docker group.
    ansible.builtin.user:
      name: "{{ admin_user }}"
      groups: docker
      append: true

  - name: Enable docker and containerd services.
    ansible.builtin.user:
      name: "{{ admin_user }}"
      groups: docker
      append: true

  - name: Enable docker.service.
    ansible.builtin.systemd:
      name: docker.service
      daemon_reload: true
      enabled: true

  - name: Enable containerd.service.
    ansible.builtin.systemd:
      name: containerd.service
      daemon_reload: true
      enabled: true
