---
- name: Install Apache
  hosts: all
  become: true

  roles:
  - deploy

#  vars:
#    source_file: ./MyWebSite/index.html
#    destination_file: /var/www/html
#  tasks:
#    - name: Check linux versions
#      debug: var=ansible_os_family
#
#    - block: #============BLOCK FOR REDHAT============
#        - name: Install Apache for RedHat
#          yum: name=httpd update_cache=yes state=latest
#
#        - name: Copy MyHomePage to servers
#          copy: src={{source_file}} dest={{destination_file}} mode=0777
#          notify: Restart Apache RedHat
#
#        - name: Starting Apache on the every boot for RedHat
#          service: name=httpd state=started enabled=yes
#
#      when: ansible_os_family == "RedHat"
